name: ManuelSgaravato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24129
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#b3472d'
    - '#d37334'
    - '#9f9958'
    - '#f7dc80'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
